In [115]:
import numpy as np
import pandas as pd
eps = np.finfo(float).eps
from numpy import log2 as log

import copy

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score


In [90]:

data = pd.read_csv('C:\\Users\\Jai\\Desktop\\adult.csv',na_values='?')

num_cols = list(data.select_dtypes(include=["number"]).columns)
cat_cols = list(data.select_dtypes(exclude=["number"]).columns)

## Drop NaN valued tuples
data = data.dropna() 
data.reset_index(drop=True,inplace=True)

print(num_cols)

['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']


In [94]:
print(len(data))
labels = pd.DataFrame(data['income'])

data.head()


45222


age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   34    Private  198693          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
4      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [103]:
print(labels.columns)
print(labels.shape[0])

Index(['income'], dtype='object')
45222


In [108]:
nn = np.zeros(labels.shape[0])

for i in range(0,labels.shape[0]):
    if(labels['income'].iloc[i] == '>50K'):
        nn[i] = 1
    else:
        nn[i] = 0

temp = pd.DataFrame(nn)
print(temp[0].value_counts())
print()
print(labels['income'].value_counts())

0.0    34014
1.0    11208
Name: 0, dtype: int64

<=50K    34014
>50K     11208
Name: income, dtype: int64


In [143]:
def getBinaryLabels(labels):
    nn = np.zeros(labels.shape[0])
    for i in range(0,labels.shape[0]):
        if(labels['income'].iloc[i] == '>50K'):
            nn[i] = 1
        else:
            nn[i] = 0
    return nn


In [112]:
test_size = 0.3
train_size = int((1 - test_size)* len(data))

df_train = data[:train_size]
df_test = data[train_size:]

df_test.reset_index(drop=True)
df_train.reset_index(drop=True)

print("Train_size",len(df_train))
print("Test_size",len(df_test))

print(df_train.shape)


Train_size 31655
Test_size 13567
(31655, 15)


In [113]:
df_train = df_train.select_dtypes(include=['number'])
df_test = df_test.select_dtypes(include=['number'])

print(df_train.shape)


(31655, 6)


In [122]:
def getProcessedData(df):
    
    # Applying MinMax Scaling
    for col in df.columns:
        mx = np.max(df[col])
        mn = np.min(df[col])
        
        df[col] = (df[col] - mn) / (mx - mn + eps)
    return df

df_train.describe()

age        fnlwgt  educational-num  capital-gain  \
count  31655.000000  3.165500e+04     31655.000000  31655.000000   
mean      38.595925  1.899570e+05        10.121687   1089.959848   
std       13.246811  1.056030e+05         2.547144   7491.437976   
min       17.000000  1.349200e+04         1.000000      0.000000   
25%       28.000000  1.175870e+05         9.000000      0.000000   
50%       37.000000  1.784210e+05        10.000000      0.000000   
75%       47.000000  2.384320e+05        13.000000      0.000000   
max       90.000000  1.490400e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  31655.000000    31655.000000  
mean      89.050766       40.936061  
std      405.175818       11.979029  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [123]:
df = getProcessedData(copy.deepcopy(df_train))


In [124]:
df.describe() 


age        fnlwgt  educational-num  capital-gain  \
count  31655.000000  31655.000000     31655.000000  31655.000000   
mean       0.295835      0.119483         0.608112      0.010900   
std        0.181463      0.071503         0.169810      0.074915   
min        0.000000      0.000000         0.000000      0.000000   
25%        0.150685      0.070482         0.533333      0.000000   
50%        0.273973      0.111672         0.600000      0.000000   
75%        0.410959      0.152305         0.800000      0.000000   
max        1.000000      1.000000         1.000000      1.000000   

       capital-loss  hours-per-week  
count  31655.000000    31655.000000  
mean       0.020443        0.407511  
std        0.093016        0.122235  
min        0.000000        0.000000  
25%        0.000000        0.397959  
50%        0.000000        0.397959  
75%        0.000000        0.448980  
max        1.000000        1.000000

In [70]:
a= np.ones((3,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [71]:
a = 2*a
a

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [72]:
b = np.ones((1,6))
b

array([[1., 1., 1., 1., 1., 1.]])

In [73]:
b = np.array([0,1,2,3,4,5])
b

array([0, 1, 2, 3, 4, 5])

In [74]:
ans = a - b


In [75]:
ans

array([[ 2.,  1.,  0., -1., -2., -3.],
       [ 2.,  1.,  0., -1., -2., -3.],
       [ 2.,  1.,  0., -1., -2., -3.]])

In [77]:
ans0 = np.sum(ans,axis = 0)
ans1 = np.sum(ans,axis = 1)

In [78]:
print(ans0.shape)
print(ans0)

print()

print(ans1.shape)
print(ans1)


(6,)
[ 6.  3.  0. -3. -6. -9.]

(3,)
[-3. -3. -3.]


In [79]:
ans1 = ans1.reshape((ans1.shape[0],1))
ans1

array([[-3.],
       [-3.],
       [-3.]])

In [125]:
ans1 = ans1**2

In [126]:
ans1

array([[9.],
       [9.],
       [9.]])

In [129]:
c = np.array([
    [0],[1],[0]
])
c

array([[0],
       [1],
       [0]])

In [132]:
con = np.concatenate((ans1,c),axis=1)
con

array([[9., 0.],
       [9., 1.],
       [9., 0.]])

In [133]:
sor = con[con[:,1].argsort()]

In [134]:
sor

array([[9., 0.],
       [9., 0.],
       [9., 1.]])

In [142]:
train_size = int((1 - test_size)* len(data))

df_train = data[:train_size]
df_test = data[train_size:]

df_test.reset_index(drop=True)
df_train.reset_index(drop=True)


# train_labels = df_train['income']
# test_labels  = df_test['income']


train_labels = pd.DataFrame(df_train['income'])
test_labels  = pd.DataFrame(df_test['income'])
print(df_train.shape)
print(train_labels.shape)

train_labels.head()

(31655, 15)
(31655, 1)


income
0  <=50K
1  <=50K
2   >50K
3   >50K
4  <=50K

In [147]:
num_cols = list(data.select_dtypes(include=["number"]).columns)
cat_cols = list(data.select_dtypes(exclude=["number"]).columns)

labels = pd.DataFrame(data['income'])

test_size = .3
train_size = int((1 - test_size)* len(data))

df_train = data[:train_size]
df_test = data[train_size:]

df_test.reset_index(drop=True)
df_train.reset_index(drop=True)

train_labels = pd.DataFrame(df_train['income'])
test_labels  = pd.DataFrame(df_test['income'])

df_train = df_train.select_dtypes(include=['number'])
df_test = df_test.select_dtypes(include=['number'])

train_labels = getBinaryLabels(train_labels)
test_labels = getBinaryLabels(test_labels)

df_train = getProcessedData(df_train)
df_test = getProcessedData(df_test)

In [153]:
print(df_train.shape)
print(train_labels)


(31655, 6)
[0. 0. 1. ... 0. 1. 0.]


In [163]:
x = df_train.values
print(type(x))

print(df_train.shape)
print(x.shape)

print()
df_train.values[20]

<class 'numpy.ndarray'>
(31655, 6)
(31655, 6)



array([0.38356164, 0.28392561, 0.53333333, 0.07298073, 0.        ,
       0.90816327])

In [190]:
sample = df_test.values[0]

x = df_train.values
x = x - sample
x = x**2
x = np.sum(x,axis=1)
x = x.reshape(x.shape[0],1)
train_labels = train_labels.reshape(train_labels.shape[0],1)

print(x.shape)
print(train_labels.shape)

(31655, 1)
(31655, 1)


In [191]:
xn = np.concatenate((x,train_labels),axis = 1)
print(xn.shape)


(31655, 2)


In [192]:
print(xn)

[[0.06182893 0.        ]
 [0.07050371 0.        ]
 [0.02178923 1.        ]
 ...
 [0.16685152 0.        ]
 [0.17167771 1.        ]
 [0.29456049 0.        ]]


In [193]:
xn = xn[xn[:,0].argsort()] 

In [210]:
print(xn.shape)
print(xn[:5])
print(xn[3][1])

print(train_labels[0])

(31655, 2)
[[4.99868882e-07 0.00000000e+00]
 [2.64300289e-05 0.00000000e+00]
 [1.26966407e-04 0.00000000e+00]
 [2.14082497e-04 0.00000000e+00]
 [2.18450502e-04 0.00000000e+00]]
0.0
[0.]


In [213]:
xn[3][1]== 1

False

In [225]:
def getPrediction(df_train, train_labels, sample, k):
    x = df_train.values
    x = x - sample
    x = x**2
    x = np.sum(x,axis=1)
    x = x.reshape(x.shape[0],1)
    train_labels = train_labels.reshape(train_labels.shape[0],1)
    
    result = np.concatenate((x,train_labels),axis = 1)
    result = result[result[:,0].argsort()] 
    
    one = 0
    zero = 0
    for i in range(0,k):
        if result[i][1] == 0:
            zero += 1
        else:
            one += 1
        
    if one>zero:
        return 1
    else:
        return 0
    
    return 1



def KNN(data, split, k, printResult = False):
    
    # we split
    num_cols = list(data.select_dtypes(include=["number"]).columns)
    cat_cols = list(data.select_dtypes(exclude=["number"]).columns)

    labels = pd.DataFrame(data['income'])

    test_size = 1 - split
    train_size = int((1 - test_size)* len(data))

    df_train = data[:train_size]
    df_test = data[train_size:]

    df_test.reset_index(drop=True)
    df_train.reset_index(drop=True)
    
    train_labels = pd.DataFrame(df_train['income'])
    test_labels  = pd.DataFrame(df_test['income'])
    
    df_train = df_train.select_dtypes(include=['number'])
    df_test = df_test.select_dtypes(include=['number'])
    
    # take out lables in binary format, train and test labels
    train_labels = getBinaryLabels(train_labels)
    test_labels = getBinaryLabels(test_labels)
    
    # normalize
    df_train = getProcessedData(df_train)
    df_test = getProcessedData(df_test)
    
    preds = np.zeros(test_labels.shape[0])
    
    for i in range(0,len(df_test)):
        preds[i] = getPrediction(df_train, train_labels, df_test.values[i], k)
    
    print(preds.shape)
    print(preds)
    print(test_labels)
    
    y_actual = test_;abe
    # accuracy: (tp + tn) / (p + n)
    accuracy = accuracy_score(y_actual,predictions)*100
    print('Accuracy      : %f' % (accuracy),"%")

    # precision tp / (tp + fp)
    precision = precision_score(y_actual,predictions)*100
    print('Precision     : %f' % precision,"%")

    # recall: tp / (tp + fn)
    recall = recall_score(y_actual,predictions)*100
    print('Recall        : %f' % recall,"%")

    # f1: 2 tp / (2 tp + fp + fn)
    f1 = f1_score(y_actual,predictions)*100
    print('F1 score      : %f' % f1,"%")

    # ROC AUC
    auc = roc_auc_score(y_actual,predictions)*100
    print("roc_auc_score :",auc,"%")
    
    # then find sum row wise
    
    # then concat with train labels
    # then sort acc. to first parameter
    # then take first k labels
    # then find max freq label 
    # append it to preds array with size as test_size
    # print if printResult = true
    # then calculate performance measures using preds and test_labels which are both binary
    
    

In [226]:
ndata = data[:100]
print(ndata.shape)

(100, 15)


In [227]:
KNN(ndata,0.7,5) 

(30,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [19]:
import csv
import random
import math
import operator

def loadDataset(filename, split, trainingSet=[] , testSet=[]):
    
    with open(filename, 'rb') as csvfile:
        lines = csv.reader(csvfile)
        
        dataset = list(lines)
        
        for x in range(len(dataset)-1):
            for y in range(4):
                dataset[x][y] = float(dataset[x][y])
                if random.random() < split:
                    trainingSet.append(dataset[x])
                else:
                    testSet.append(dataset[x])
    
    return trainSet,testSet

In [20]:
def euclideanDistance(instance1, instance2, length):
    distance = 0
    
    for x in range(length):
        distance += pow((instance1[x] - instance2[x]), 2)
    
    return math.sqrt(distance)

In [21]:
def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist))
    
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    
    for x in range(k):
        neighbors.append(distances[x][0])
    
    return neighbors

In [22]:
def getResponse(neighbors):
    classVotes = {}
    
    for x in range(len(neighbors)):
        response = neighbors[x][-1]
        
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
            sortedVotes = sorted(classVotes.iteritems(),
            reverse=True)
   
    return sortedVotes[0][0]

In [23]:
def getAccuracy(testSet, predictions):
    correct = 0
    
    for x in range(len(testSet)):
        key=operator.itemgetter(1),
        if testSet[x][-1] == predictions[x]:
            correct += 1

    return (correct/float(len(testSet))) * 100.0

In [24]:
def main():
    
    # prepare data
    trainingSet=[]
    testSet=[]
    
    split = 0.67
    
    loadDataset('knndat.data', split, trainingSet, testSet)
    
    print('Train set: ' + repr(len(trainingSet)))
    print('Test set: ' + repr(len(testSet)))
    
    # generate predictions
    predictions=[]
    
    k=3
    
    for x in range(len(testSet)):
        neighbors = getNeighbors(trainingSet, testSet[x], k)
        result = getResponse(neighbors)
        predictions.append(result)
        print('> predicted=' + repr(result) + ', actual=' + repr(testSet[x][-1]))
    accuracy = getAccuracy(testSet, predictions)
    print('Accuracy: ' + repr(accuracy) + '%')


In [15]:
# data = pd.read_csv('C:\\Users\\Jai\\Desktop\\adult.csv',na_values='?')
# data = data.dropna()
# print(len(data))
# data.to_csv("processed_data.csv")

45222


In [17]:
data = pd.read_csv('processed_data.csv')
print(len(data))
data.head()

45222


Unnamed: 0  age  workclass  fnlwgt     education  educational-num  \
0           0   25    Private  226802          11th                7   
1           1   38    Private   89814       HS-grad                9   
2           2   28  Local-gov  336951    Assoc-acdm               12   
3           3   44    Private  160323  Some-college               10   
4           5   34    Private  198693          10th                6   

       marital-status         occupation   relationship   race gender  \
0       Never-married  Machine-op-inspct      Own-child  Black   Male   
1  Married-civ-spouse    Farming-fishing        Husband  White   Male   
2  Married-civ-spouse    Protective-serv        Husband  White   Male   
3  Married-civ-spouse  Machine-op-inspct        Husband  Black   Male   
4       Never-married      Other-service  Not-in-family  White   Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States  <=50K  
1             0             0              50  United-States  <=50K  
2             0             0              40  United-States   >50K  
3          7688             0              40  United-States   >50K  
4             0             0              30  United-States  <=50K

In [25]:
train,test = loadDataset('processed_data.csv',0.7)


Error: iterator should return strings, not bytes (did you open the file in text mode?)